name: sudoku_dart
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  uuid: ^3.0.6
  tuple: ^2.0.0
  json_annotation: ^4.5.0


dev_dependencies:
  test: ^1.21.3
  flutter_lints: ^2.0.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
